title: Lingchun Zhang's Homepage 
page-top-title: Lingchun Zhang
top-section-bg-text: Deep Learning
home-subtitle: Lingchun Zhang&ensp;|&ensp;张令春
copyright-text: '&copy; Lingchun Zhang . All Rights Reserved.'
